[package]
name = "sen-desktop"
version = "0.2.0"
description = "Sen lotus desktop companion"
authors = ["Loccao102"]
edition = "2021"

[lib]
name = "sen_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-global-shortcut = "2"
tauri-plugin-autostart = "2"
